# Generated by Django 5.0.6 on 2024-07-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='favicon.jpg', null=True, upload_to=''),
        ),
    ]
