# Generated by Django 5.0.6 on 2024-08-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='favicon.jpg', null=True, upload_to=''),
        ),
    ]
